### Conversion of MeSH *rest* to SKOS format
##  - version 1.1.1 2026-02-09
## Run the query - copy this file to Apache Jena data dir, STOP Fuseki instance, and run:
#  tdb2_tdbquery --loc=databases/mesh --query=mesh-rest-to-skos.rq --time > mesh-skos-rest.ttl
#
PREFIX mesh:  <http://id.nlm.nih.gov/mesh/>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesht: <http://www.medvik.cz/schema/mesh/vocab/#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {

  ?d skos:altLabel ?palabel, ?alabel, ?clabel .

  ?d skos:altLabel ?talabel, ?ptlabel .

  ?d skos:hiddenLabel ?hlabel, ?hclabel .

  ?d skos:scopeNote ?scopeNote, ?tscopeNote .

  ?d skos:note ?annotation, ?tannotation .

  ?d skos:editorialNote ?considerAlso, ?tconsiderAlso .

  ?d skos:historyNote ?historyNote, ?thistoryNote .

}
WHERE {

  # Bind the descriptor for testing
  #BIND(mesh:D000086582 AS ?d)
  #BIND(mesh:D017239 AS ?d)
  #BIND(mesh:D000077102 AS ?d)
  #BIND(mesh:D004232 AS ?d)
  #BIND(mesh:D000077102 AS ?d)

  VALUES ?type {
    meshv:TopicalDescriptor
    meshv:GeographicalDescriptor
    meshv:PublicationType
    meshv:CheckTag
    meshv:Qualifier
  }

  ?d rdf:type ?type .
  ?d meshv:preferredConcept ?c .
  FILTER NOT EXISTS { ?c meshv:active false }

  OPTIONAL {
    ?c meshv:term ?ptc .
    ?ptc meshv:prefLabel ?ptlabel
  }

  OPTIONAL {
    ?c mesht:term ?ctt .
    ?ctt mesht:prefLabel ?talabel
  }

  OPTIONAL {
    ?c meshv:narrowerConcept|meshv:broaderConcept|meshv:relatedConcept ?npc .
    {
      ?npc meshv:preferredTerm ?npct .
      ?npct meshv:prefLabel ?alabel
    }
    UNION
    {
      ?npc mesht:preferredTerm ?npctt .
      ?npctt mesht:prefLabel ?alabel
    }
  }

  OPTIONAL {
    ?c mesht:narrowerConcept|mesht:broaderConcept|mesht:relatedConcept ?ncc .
    ?ncc mesht:preferredTerm ?nccp .
    ?nccp mesht:prefLabel ?clabel

    OPTIONAL {
      ?ncc mesht:term ?ncct .
      ?ncct mesht:prefLabel ?hclabel
    }

  }

  OPTIONAL {
    ?c meshv:narrowerConcept|meshv:broaderConcept|meshv:relatedConcept ?nc .
    {
      ?nc meshv:preferredTerm|meshv:term ?ncnp .
      ?ncnp meshv:altLabel ?hlabel
    }
    UNION
    {
      ?nc mesht:term ?ncnp .
      ?ncnp mesht:prefLabel ?hlabel
    }
  }

  # Scope notes
  OPTIONAL { ?c meshv:scopeNote ?scopeNote }
  OPTIONAL { ?c mesht:scopeNote ?tscopeNote }

  # Annotations
  OPTIONAL { ?d meshv:annotation ?annotation }
  OPTIONAL { ?d mesht:annotation ?tannotation }

  # ConsiderAlso / editorial notes
  OPTIONAL { ?d meshv:considerAlso ?considerAlso }
  OPTIONAL { ?d mesht:considerAlso ?tconsiderAlso }

  # History notes
  OPTIONAL { ?d meshv:historyNote ?historyNote }
  OPTIONAL { ?d mesht:historyNote ?thistoryNote }

}
#LIMIT 10000

